# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    
     #monolog config
    app.formatter:
        class: App\Service\Formatter
        public: true
        arguments: ['@logger']
        #arguments: [~, ~, true]
        tags:
            - { name: monolog.logger, channel: trace }


    annuaire1212_annotation_listener:
        class: App\Listener\AnnotationListener
        public: true
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        arguments: ['@service_container']
            #- { type: service, id: service_container }
        
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
